disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - modifier_order
  - redundant_nil_coalescing
  - sorted_first_last
  - unavailable_function
  - unused_import
included:
  - ios
excluded:
  - .build
  - DerivedData
  - Pods
line_length:
  warning: 120
  error: 160
