import {
  createValidationResult,
  isNonEmptyString,
  isPlainObject,
  requireFields,
  validateUniqueIds
} from "./schemaValidation.js";

export const MULTIPLE_CHOICE_DRAFT_UNIT_BATCH_PROMPT_SCHEMA_NAME =
  "shibei_v2_multiple_choice_draft_unit_batch";

const MULTIPLE_CHOICE_CORE_QUESTION_SCHEMA = {
  type: "object",
  required: [
    "id",
    "type",
    "practiceGoalId",
    "stem",
    "correctUnderstanding",
    "misconception",
    "explanation",
    "sourceAnchorId"
  ],
  additionalProperties: false,
  properties: {
    id: { type: "string" },
    type: { enum: ["multiple_choice"] },
    practiceGoalId: { type: "string" },
    stem: { type: "string" },
    correctUnderstanding: { type: "string" },
    misconception: { type: "string" },
    explanation: { type: "string" },
    sourceAnchorId: { type: "string" }
  }
};

export const MULTIPLE_CHOICE_DRAFT_UNIT_BATCH_OUTPUT_SCHEMA = {
  name: MULTIPLE_CHOICE_DRAFT_UNIT_BATCH_PROMPT_SCHEMA_NAME,
  type: "object",
  required: ["unitId", "questions"],
  additionalProperties: false,
  properties: {
    unitId: { type: "string" },
    questions: {
      type: "array",
      items: MULTIPLE_CHOICE_CORE_QUESTION_SCHEMA
    }
  }
};

export function validateMultipleChoiceDraftUnitBatchOutput(
  output,
  { unitId, questionPlanIds = new Set(), sourceAnchorId } = {}
) {
  const errors = [];

  if (!isPlainObject(output)) {
    return createValidationResult(["multipleChoiceDraftUnitBatch output must be an object"]);
  }

  if (!isNonEmptyString(output.unitId)) {
    errors.push("multipleChoiceDraftUnitBatch.unitId is required");
  } else if (unitId && output.unitId !== unitId) {
    errors.push(`multipleChoiceDraftUnitBatch.unitId must match ${unitId}`);
  }

  if (!Array.isArray(output.questions)) {
    errors.push("multipleChoiceDraftUnitBatch.questions must be an array");
    return createValidationResult(errors);
  }

  if (output.questions.length !== questionPlanIds.size) {
    errors.push(`multipleChoiceDraftUnitBatch.questions must contain ${questionPlanIds.size} multiple choice questions`);
  }

  validateUniqueIds(output.questions, "multipleChoiceDraftUnitBatch.questions", errors);

  output.questions.forEach((question, index) => {
    validateMultipleChoiceCoreQuestion(question, {
      path: `multipleChoiceDraftUnitBatch.questions[${index}]`,
      questionPlanIds,
      sourceAnchorId,
      errors
    });
  });

  return createValidationResult(errors);
}

function validateMultipleChoiceCoreQuestion(question, {
  path,
  questionPlanIds,
  sourceAnchorId,
  errors
}) {
  if (!isPlainObject(question)) {
    errors.push(`${path} must be an object`);
    return;
  }

  requireFields(
    question,
    [
      "id",
      "type",
      "practiceGoalId",
      "stem",
      "correctUnderstanding",
      "misconception",
      "explanation",
      "sourceAnchorId"
    ],
    path,
    errors
  );

  if (question.type !== "multiple_choice") {
    errors.push(`${path}.type must be multiple_choice`);
  }
  if (isNonEmptyString(question.id) && !questionPlanIds.has(question.id)) {
    errors.push(`${path}.id must match a multiple_choice question plan id`);
  }
  if (sourceAnchorId && question.sourceAnchorId !== sourceAnchorId) {
    errors.push(`${path}.sourceAnchorId must match ${sourceAnchorId}`);
  }
  if (question.options !== undefined) {
    errors.push(`${path}.options must be generated by multipleChoiceOptionSetUnitBatch`);
  }
  if (question.correctOptionId !== undefined) {
    errors.push(`${path}.correctOptionId must be generated by multipleChoiceOptionSetUnitBatch`);
  }
}
